sudo: required

dist: trusty

services:
    - docker

language: node_js
node_js: 12

# before_script:
#     - my_script

script:
    - npm ci
    - npm run build
    - npm run test

# after_script:
#     - my_script

notifications:
    email:
        recipients:
            - simonpiscitelli@gmail.com
        on_success: never # default: change
        on_failure: change # default: always
env:
    global:
        - $BRANCH=${TRAVIS_BRANCH}
